### ISSUE TITLE
Timeout on both ROM and EEPROM Dump

### ISSUE THREAD

**Issue by Eloeri** [celerizer/activity-meter-rom-dumper#1]
Hello, 

I am using this software on a hacked 3DSXL through the twilight menu, with original HeartGold and Soul Silver cartridges. I get a good test (which wiped out a few thousand watts), however when selecting either dumping the ROM or the EEPROM, it goes through the process but for the EEPROM, it times out consistenly on `216/512` and for ROM, `bf80/c000`.

If you know how I can get past these issues, please let me know, thank you!

**Comment by celerizer** [comment]
Hi, this is an edited version of a repo hosted outside GitHub. The original repo is here: https://gitlab.ulyssis.org/pcy/pokewalker-rom-dumper

The original repo dumped from a Pokewalker, but this dumps from a [Nintendo DS Activity Meter](https://nintendo.fandom.com/wiki/Activity_Meter) using a Personal Trainer Walking cartridge, not Pokemon. You'll need to contact the original author about issues if you're dumping from a Pokewalker.

I'll edit the Readme to reflect this and hopefully avoid any more confusion

**Comment by Eloeri** [comment]
Ah, my apologies! I did read the project name as activity-meter-dumper, however since the link in the readme pointed to the same .nds hombrew as PoroCYon's, I assumed you would be able to help me. Sorry for the hassle and thank you for responding!
